image: archlinux
packages:
  - systemd
  - linux-api-headers
  - libx11
  - libxrandr
  - libxext
  - ddcutil
  - libmodule
  - cmake
  - polkit
  - libusb
  - libjpeg-turbo
sources:
  - https://github.com/FedeDP/Clightd
tasks:
  - prepare: |
      cd Clightd
      mkdir build build-no-gamma build-no-dpms build-no-ddc build-no-screen build-no-yoctolight build-no-extras
      (cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_DDC=1 -DENABLE_SCREEN=1 -DENABLE_YOCTOLIGHT=1 ..)
      (cd build-no-gamma && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_DPMS=1 -DENABLE_DDC=1 -DENABLE_SCREEN=1 -DENABLE_YOCTOLIGHT=1 ..)
      (cd build-no-dpms && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DDC=1 -DENABLE_SCREEN=1 -DENABLE_YOCTOLIGHT=1 ..)
      (cd build-no-ddc && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_SCREEN=1 -DENABLE_YOCTOLIGHT=1 ..)
      (cd build-no-screen && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_DDC=1 -DENABLE_YOCTOLIGHT=1 ..)
      (cd build-no-yoctolight && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_DDC=1 -DENABLE_SCREEN=1 ..)
      (cd build-no-extras && cmake -DCMAKE_BUILD_TYPE=Debug ..)
  - build: |
      cd Clightd
      (cd build && make)
      (cd build-no-gamma && make)
      (cd build-no-dpms && make)
      (cd build-no-ddc && make)
      (cd build-no-screen && make)
      (cd build-no-yoctolight && make)
      (cd build-no-extras && make)
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
