image: archlinux
packages:
  - systemd
  - linux-api-headers
  - libx11
  - libxrandr
  - libxext
  - libxss
  - ddcutil
  - libmodule
  - cmake
  - polkit
sources:
  - https://github.com/FedeDP/Clightd
tasks:
  - prepare: |
      cd Clightd
      mkdir build build-no-gamma build-no-dpms build-no-idle build-no-ddc build-no-extras
      (cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_DDC=1 -DENABLE_IDLE=1 ..)
      (cd build-no-gamma && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_DPMS=1 -DENABLE_DDC=1 -DENABLE_IDLE=1 ..)
      (cd build-no-dpms && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DDC=1 -DENABLE_IDLE=1 ..)
      (cd build-no-idle && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_DDC=1 ..)
      (cd build-no-ddc && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_IDLE=1 ..)
      (cd build-no-extras && cmake -DCMAKE_BUILD_TYPE=Debug ..)
  - build: |
      cd Clightd
      (cd build && make)
      (cd build-no-gamma && make)
      (cd build-no-dpms && make)
      (cd build-no-idle && make)
      (cd build-no-ddc && make)
      (cd build-no-extras && make)
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
